# Generated by Django 5.1.5 on 2025-02-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.AddField(
            model_name='customer',
            name='branch',
            field=models.CharField(default='branch', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='registered_no',
            field=models.CharField(default='reg', max_length=50),
        ),
    ]
