# Generated by Django 5.1.5 on 2025-02-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_customer_password_alter_customer_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_updated',
            field=models.BooleanField(default=False),
        ),
    ]
