# Generated by Django 5.1.5 on 2025-02-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='old_cart',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
